export const privateRoutes = [
  { path: "/home", component: "Home" },
  // { path: "/family-details", component: "FamilyDetails" },
  { path: "/upload-photo", component: "UploadPhoto" },
  { path: "/hobby-interest", component: "Hobby" },
  { path: "/profile-preview", component: "ProfilePreview" },
  { path: "/my-profile", component: "MyProfile" },
  { path: "/my-photos", component: "MyPhotos" },
  { path: "/matches", component: "Matches" },
  { path: "/settings", component: "Settings" },
  { path: "/partner-preferences", component: "PartnerPreferences" },
  // { path: "/about-me", component: "CreateProfile" },
  { path: "/profile-creation/step/:step", component: "CreateProfile" },
  { path: "/profile-creation/about-me", component: "CreateProfile" },
  { path: "/profile-creation/family-details", component: "CreateProfile" },
  { path: "/inbox", component: "Inbox" },
];
